# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasaSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyaboutmoon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='storyaboutmoon',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='storyaboutmoon',
            name='type',
            field=models.CharField(blank=True, choices=[('Myth', 'Myth'), ('Fact', 'Fact'), ('Story', 'Story')], max_length=10, null=True),
        ),
    ]
