# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasaSpace', '0002_auto_20160423_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
