# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasaSpace', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oxygen', models.IntegerField(default=20)),
                ('Hydrogen', models.IntegerField(default=10)),
                ('Water', models.IntegerField(default=10)),
                ('Poop', models.IntegerField(default=10)),
                ('Fuel', models.IntegerField(default=0)),
                ('CarbonDioxide', models.IntegerField(default=10)),
            ],
        ),
    ]
