# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasaSpace', '0007_mytent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytent',
            name='Food',
            field=models.IntegerField(default=10),
        ),
    ]
